services:
  mysql-scraping:
    image: mysql:8.0
    container_name: mysql-scraping
    restart: always
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - scraping-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    platform: linux/amd64
    environment:
      PMA_HOST: mysql-scraping
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - scraping-net


volumes:
  mysql_data:

networks:
  scraping-net:
